#!/bin/bash
# Historic overshoot rerun: RawOutputRepeat FireOn + RawOutput Wetland merge.
# Use with: WIEMIP_CONFIG=config_overshoot_historic_rerun.sh ./run_historic_overshoot_rerun.sh

WET_RUN="gs://wiemip/OvershootOutput/RawOutput/historic/Special_historic_Wetland_split/all_merged_restored"
BASE_RUN="gs://wiemip/OvershootOutput/RawOutputRepeat/historic/Special_historic_FireOn/Special_historic_FireOn_1_Split5/all_merged_filtered"

export OUTPUT_DIR="/mnt/disks/wiemip-data/re-run-overshoot"
export GCM_PATTERN="historical"
export EXPERIMENT="FireOn"
export PROCESS="noProcess"
export PROCESS_FROM_LIST="true"
export OVERSHOOT="true"
export PATH_GS_MERGE_CSV="path_gs_merge_overshoot_rerun.csv"
export FILTERED="true"
export PROCESS_ROWS="all"
export PROCESS_ROW_LIST="2"
export SKIP_DOWNLOAD_IF_EXISTS="false"
export MAX_WORKERS="1"
# RawOutputRepeat Split5 active bbox (inclusive row/col ends); full WIEMIP grid 123x720
export MERGE_SPATIAL_BBOX="34,108,0,719"
export FULL_SPATIAL_SHAPE="123,720"
export FIX_FILTERED_TIME_AND_COORDS="true"
export ADD_COORDS_BEFORE_FIX="true"
export RUN_MASK="/mnt/disks/wiemip-data/dvmdostem-wiemip/post-processing/run-mask2.nc"

VAR_NAMES=(ALD AVLN BURNSOIL2AIRC BURNVEG2AIRC CH4EFFLUXTOT DWDC EET GPP LAI LFNVC LFVC NETNMIN NPP NUPTAKELAB NUPTAKEST ORGN RHSOM SNOWTHICK SOC SOC0_100cm SWE TLAYER TRANSPIRATION VEGC VEGNTOT VWCLAYER WATERTAB cSoil gpp npp ra cSoilBelow1m fVegSoil fNup)

export AGG_ALD="mean"
export AGG_AVLN="mean"
export AGG_BURNSOIL2AIRC="sum"
export AGG_BURNVEG2AIRC="sum"
export AGG_CH4EFFLUXTOT="sum"
export AGG_DWDC="mean"
export AGG_EET="sum"
export AGG_GPP="sum"
export AGG_LAI="mean"
export AGG_LFNVC="sum"
export AGG_LFVC="sum"
export AGG_NETNMIN="sum"
export AGG_NPP="sum"
export AGG_NUPTAKELAB="sum"
export AGG_NUPTAKEST="sum"
export AGG_ORGN="mean"
export AGG_QRUNOFF="sum"
export AGG_RHSOM="sum"
export AGG_SNOWTHICK="mean"
export AGG_SOC="mean"
export AGG_SOC0_100cm="mean"
export AGG_SWE="mean"
export AGG_TLAYER="mean"
export AGG_TRANSPIRATION="sum"
export AGG_VEGC="mean"
export AGG_VEGNTOT="mean"
export AGG_VWCLAYER="mean"
export AGG_WATERTAB="mean"
